/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gestorprocesos.instructionMaker;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import programcontroller.FileLoader;
import gestorprocesos.Process;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Kevin
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.cmb_box_qbit.setVisible(false);
        this.labelQbit.setVisible(false);
        this.jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Memoria"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLoadFile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProcesses = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        textInput = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cmdButton = new javax.swing.JButton();
        lblInterruptionWarning = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtPC_CPU1 = new javax.swing.JTextField();
        txtIR_CPU1 = new javax.swing.JTextField();
        txtAC_CPU1 = new javax.swing.JTextField();
        txtAX_CPU1 = new javax.swing.JTextField();
        txtBX_CPU1 = new javax.swing.JTextField();
        txtCX_CPU1 = new javax.swing.JTextField();
        txtDX_CPU1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtPC_CPU2 = new javax.swing.JTextField();
        txtIR_CPU2 = new javax.swing.JTextField();
        txtAC_CPU2 = new javax.swing.JTextField();
        txtAX_CPU2 = new javax.swing.JTextField();
        txtBX_CPU2 = new javax.swing.JTextField();
        txtCX_CPU2 = new javax.swing.JTextField();
        txtDX_CPU2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnExecute = new javax.swing.JButton();
        btnNextStep = new javax.swing.JButton();
        btnClean = new javax.swing.JButton();
        btnStats = new javax.swing.JButton();
        start_Btn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnConfig = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        cmb_box_Planification = new javax.swing.JComboBox<>();
        labelQbit = new javax.swing.JLabel();
        cmb_box_qbit = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableMemory = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDisc = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        cmb_box_MemoryA = new javax.swing.JComboBox<>();
        labelQbit2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivo(s)"));

        btnLoadFile.setBackground(new java.awt.Color(51, 153, 255));
        btnLoadFile.setForeground(new java.awt.Color(255, 255, 255));
        btnLoadFile.setText("Cargar archivo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnLoadFile)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnLoadFile)
                .addGap(15, 15, 15))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Procesos"));

        tableProcesses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Procesos", "Estados"
            }
        ));
        tableProcesses.setEnabled(false);
        jScrollPane1.setViewportView(tableProcesses);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pantalla", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        jLabel15.setForeground(new java.awt.Color(51, 153, 255));
        jLabel15.setText(">>Ingrese un valor:");

        textInput.setEditable(false);
        textInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textInputKeyTyped(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        cmdButton.setBackground(new java.awt.Color(51, 153, 255));
        cmdButton.setForeground(new java.awt.Color(255, 255, 255));
        cmdButton.setText("Ok");
        cmdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdButtonActionPerformed(evt);
            }
        });

        lblInterruptionWarning.setVisible(false);
        lblInterruptionWarning.setText("jLabel16");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(textInput)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblInterruptionWarning)
                .addGap(229, 229, 229))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInterruptionWarning)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("BPC's"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BPC actual CPU 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPC_CPU1.setEditable(false);
        txtPC_CPU1.setBackground(new java.awt.Color(255, 255, 255));
        txtPC_CPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPC_CPU1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtPC_CPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 60, -1));

        txtIR_CPU1.setEditable(false);
        txtIR_CPU1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtIR_CPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 52, 60, -1));

        txtAC_CPU1.setEditable(false);
        txtAC_CPU1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtAC_CPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 80, 60, -1));

        txtAX_CPU1.setEditable(false);
        txtAX_CPU1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtAX_CPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 120, 60, -1));

        txtBX_CPU1.setEditable(false);
        txtBX_CPU1.setBackground(new java.awt.Color(255, 255, 255));
        txtBX_CPU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBX_CPU1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtBX_CPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 148, 60, -1));

        txtCX_CPU1.setEditable(false);
        txtCX_CPU1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtCX_CPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 176, 60, -1));

        txtDX_CPU1.setEditable(false);
        txtDX_CPU1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtDX_CPU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 204, 60, -1));

        jLabel1.setText("PC");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jLabel2.setText("IR");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 30, 30));

        jLabel3.setText("AC");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jLabel4.setText("AX");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel5.setText("BX");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel6.setText("CX");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel7.setText("DX");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BPC actual CPU 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(51, 153, 255))); // NOI18N

        txtPC_CPU2.setEditable(false);
        txtPC_CPU2.setBackground(new java.awt.Color(255, 255, 255));

        txtIR_CPU2.setEditable(false);
        txtIR_CPU2.setBackground(new java.awt.Color(255, 255, 255));

        txtAC_CPU2.setEditable(false);
        txtAC_CPU2.setBackground(new java.awt.Color(255, 255, 255));

        txtAX_CPU2.setEditable(false);
        txtAX_CPU2.setBackground(new java.awt.Color(255, 255, 255));
        txtAX_CPU2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAX_CPU2ActionPerformed(evt);
            }
        });

        txtBX_CPU2.setEditable(false);
        txtBX_CPU2.setBackground(new java.awt.Color(255, 255, 255));

        txtCX_CPU2.setEditable(false);
        txtCX_CPU2.setBackground(new java.awt.Color(255, 255, 255));

        txtDX_CPU2.setEditable(false);
        txtDX_CPU2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setText("PC");

        jLabel9.setText("IR");

        jLabel10.setText("AC");

        jLabel11.setText("AX");

        jLabel12.setText("BX");

        jLabel13.setText("CX");

        jLabel14.setText("DX");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCX_CPU2)
                    .addComponent(txtBX_CPU2)
                    .addComponent(txtAX_CPU2)
                    .addComponent(txtDX_CPU2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPC_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIR_CPU2)
                    .addComponent(txtAC_CPU2))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addComponent(jLabel13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPC_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIR_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAC_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAX_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBX_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCX_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDX_CPU2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Comandos"));

        btnExecute.setBackground(new java.awt.Color(51, 153, 255));
        btnExecute.setForeground(new java.awt.Color(255, 255, 255));
        btnExecute.setText("Ejecutar");
        btnExecute.setEnabled(false);

        btnNextStep.setBackground(new java.awt.Color(51, 153, 255));
        btnNextStep.setForeground(new java.awt.Color(255, 255, 255));
        btnNextStep.setText("Siguiente");
        btnNextStep.setEnabled(false);

        btnClean.setBackground(new java.awt.Color(51, 153, 255));
        btnClean.setForeground(new java.awt.Color(255, 255, 255));
        btnClean.setText("Limpiar");

        btnStats.setBackground(new java.awt.Color(51, 153, 255));
        btnStats.setForeground(new java.awt.Color(255, 255, 255));
        btnStats.setText("Estadistica");
        btnStats.setEnabled(false);

        start_Btn.setBackground(new java.awt.Color(51, 153, 255));
        start_Btn.setForeground(new java.awt.Color(255, 255, 255));
        start_Btn.setText("Iniciar");
        start_Btn.setEnabled(false);
        start_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(start_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExecute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextStep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClean)
                .addGap(18, 18, 18)
                .addComponent(btnStats)
                .addGap(17, 17, 17))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExecute)
                    .addComponent(btnNextStep)
                    .addComponent(btnClean)
                    .addComponent(btnStats)
                    .addComponent(start_Btn))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Configuracion"));

        btnConfig.setBackground(new java.awt.Color(0, 51, 255));
        btnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/settings-icon-6.png"))); // NOI18N
        btnConfig.setMaximumSize(new java.awt.Dimension(30, 30));
        btnConfig.setMinimumSize(new java.awt.Dimension(30, 30));
        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Planificadores"));
        jPanel10.setToolTipText("");

        cmb_box_Planification.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FCFS", "SPN", "SRT", "RR", "HRRN" }));
        cmb_box_Planification.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_box_PlanificationItemStateChanged(evt);
            }
        });
        cmb_box_Planification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_box_PlanificationActionPerformed(evt);
            }
        });

        labelQbit.setText("q = ");

        cmb_box_qbit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        cmb_box_qbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_box_qbitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cmb_box_Planification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(labelQbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_box_qbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cmb_box_qbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(labelQbit)
                .addComponent(cmb_box_Planification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Memoria principal"));

        tableMemory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Pos", "Valor en memoria"
            }
        ));
        tableMemory.setEnabled(false);
        jScrollPane2.setViewportView(tableMemory);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Disco"));

        tableDisc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Pos", "Valor en disco"
            }
        ));
        tableDisc.setEnabled(false);
        jScrollPane3.setViewportView(tableDisc);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Planifiacadores"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPU 1", "Tiempo", "Tiempo", "Tiempo"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane5.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CPU 2", "Tiempo", "Tiempo", "Tiempo"
            }
        ));
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane6.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Planificadores"));
        jPanel14.setToolTipText("");

        cmb_box_MemoryA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fijo", "Dinámico", "Segmentación", "Paginación" }));
        cmb_box_MemoryA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_box_MemoryAItemStateChanged(evt);
            }
        });
        cmb_box_MemoryA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_box_MemoryAActionPerformed(evt);
            }
        });

        labelQbit2.setText("Algoritmo de gestión de memoria");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQbit2)
                    .addComponent(cmb_box_MemoryA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(labelQbit2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmb_box_MemoryA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(21, 21, 21)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPC_CPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPC_CPU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPC_CPU1ActionPerformed

    private void txtBX_CPU1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBX_CPU1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBX_CPU1ActionPerformed

    private void txtAX_CPU2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAX_CPU2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAX_CPU2ActionPerformed

    private void btnLoadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadFileActionPerformed

    }//GEN-LAST:event_btnLoadFileActionPerformed

    private void tableProcessesComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tableProcessesComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tableProcessesComponentAdded

    private void start_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_start_BtnActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfigActionPerformed

    private void cmb_box_PlanificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_box_PlanificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_box_PlanificationActionPerformed

    private void cmb_box_PlanificationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_box_PlanificationItemStateChanged
        if (this.cmb_box_Planification.getSelectedItem().equals("RR")) {
            this.cmb_box_qbit.setVisible(true);
            this.labelQbit.setVisible(true);
        } else {
            this.cmb_box_qbit.setVisible(false);
            this.labelQbit.setVisible(false);
        }
    }//GEN-LAST:event_cmb_box_PlanificationItemStateChanged

    private void cmb_box_MemoryAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_box_MemoryAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_box_MemoryAActionPerformed

    private void cmb_box_MemoryAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_box_MemoryAItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_box_MemoryAItemStateChanged

    private void cmdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdButtonActionPerformed

    private void cmb_box_qbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_box_qbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_box_qbitActionPerformed

    private void textInputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textInputKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_textInputKeyTyped

    public void setlblInterruptionWarning(String text) {
        lblInterruptionWarning.setText(text);
    }
    
    public JLabel getlblInterruptionWarning() {
        return lblInterruptionWarning;
    }
    
    public JButton getcmdButton() {
        return cmdButton;
    }
    
    public JComboBox<String> getCmb_box_Planification() {
        return cmb_box_Planification;
    }

    public void setCmb_box_Planification(JComboBox<String> cmb_box_Planification) {
        this.cmb_box_Planification = cmb_box_Planification;
    }

    public JComboBox<String> getCmb_box_MemoryA() {
        return cmb_box_MemoryA;
    }

    public void setCmb_box_MemoryA(JComboBox<String> cmb_box_MemoryA) {
        this.cmb_box_MemoryA = cmb_box_MemoryA;
    }

    public JComboBox<String> getCmb_box_qbit() {
        return cmb_box_qbit;
    }

    public void setCmb_box_qbit(JComboBox<String> cmb_box_qbit) {
        this.cmb_box_qbit = cmb_box_qbit;
    }

    public JButton getStart_Btn() {
        return start_Btn;
    }

    public void setStart_Btn(JButton start_Btn) {
        this.start_Btn = start_Btn;
    }

    public JButton getBtnConfig() {
        return btnConfig;
    }

    public void setBtnConfig(JButton btnConfig) {
        this.btnConfig = btnConfig;
    }

    
    public JButton getBtnClean() {
        return btnClean;
    }

    public void setBtnClean(JButton btnClean) {
        this.btnClean = btnClean;
    }

    public JButton getBtnExecute() {
        return btnExecute;
    }

    public void setBtnExecute(JButton btnExecute) {
        this.btnExecute = btnExecute;
    }

    public JButton getBtnLoadFile() {
        return btnLoadFile;
    }

    public void setBtnLoadFile(JButton btnLoadFile) {
        this.btnLoadFile = btnLoadFile;
    }

    public JButton getBtnNextStep() {
        return btnNextStep;
    }

    public void setBtnNextStep(JButton btnNextStep) {
        this.btnNextStep = btnNextStep;
    }

    public JButton getBtnStats() {
        return btnStats;
    }

    public void setBtnStats(JButton btnStats) {
        this.btnStats = btnStats;
    }

    public JTextArea getjTextArea1() {
        return jTextArea1;
    }

    public void setjTextArea1(JTextArea jTextArea1) {
        this.jTextArea1 = jTextArea1;
    }

    public JTable getTableDisc() {
        return tableDisc;
    }

    public void setTableDisc(JTable tableDisc) {
        this.tableDisc = tableDisc;
    }

    public JTable getTableMemory() {
        return tableMemory;
    }

    public void setTableMemory(JTable tableMemory) {
        this.tableMemory = tableMemory;
    }

    public JTable getTableProcesses() {
        return tableProcesses;
    }

    public void setTableProcesses(JTable tableProcesses) {
        this.tableProcesses = tableProcesses;
    }

    public JTextField getTextInput() {
        return textInput;
    }

    public void setTextInput(JTextField textInput) {
        this.textInput = textInput;
    }

    public JTextField getTxtAC_CPU1() {
        return txtAC_CPU1;
    }

    public void setTxtAC_CPU1(JTextField txtAC_CPU1) {
        this.txtAC_CPU1 = txtAC_CPU1;
    }

    public JTextField getTxtAC_CPU2() {
        return txtAC_CPU2;
    }

    public void setTxtAC_CPU2(JTextField txtAC_CPU2) {
        this.txtAC_CPU2 = txtAC_CPU2;
    }

    public JTextField getTxtAX_CPU1() {
        return txtAX_CPU1;
    }

    public void setTxtAX_CPU1(JTextField txtAX_CPU1) {
        this.txtAX_CPU1 = txtAX_CPU1;
    }

    public JTextField getTxtAX_CPU2() {
        return txtAX_CPU2;
    }

    public void setTxtAX_CPU2(JTextField txtAX_CPU2) {
        this.txtAX_CPU2 = txtAX_CPU2;
    }

    public JTextField getTxtBX_CPU1() {
        return txtBX_CPU1;
    }

    public void setTxtBX_CPU1(JTextField txtBX_CPU1) {
        this.txtBX_CPU1 = txtBX_CPU1;
    }

    public JTextField getTxtBX_CPU2() {
        return txtBX_CPU2;
    }

    public void setTxtBX_CPU2(JTextField txtBX_CPU2) {
        this.txtBX_CPU2 = txtBX_CPU2;
    }

    public JTextField getTxtCX_CPU1() {
        return txtCX_CPU1;
    }

    public void setTxtCX_CPU1(JTextField txtCX_CPU1) {
        this.txtCX_CPU1 = txtCX_CPU1;
    }

    public JTextField getTxtCX_CPU2() {
        return txtCX_CPU2;
    }

    public void setTxtCX_CPU2(JTextField txtCX_CPU2) {
        this.txtCX_CPU2 = txtCX_CPU2;
    }

    public JTextField getTxtDX_CPU1() {
        return txtDX_CPU1;
    }

    public void setTxtDX_CPU1(JTextField txtDX_CPU1) {
        this.txtDX_CPU1 = txtDX_CPU1;
    }

    public JTextField getTxtDX_CPU2() {
        return txtDX_CPU2;
    }

    public void setTxtDX_CPU2(JTextField txtDX_CPU2) {
        this.txtDX_CPU2 = txtDX_CPU2;
    }

    public JTextField getTxtIR_CPU1() {
        return txtIR_CPU1;
    }

    public void setTxtIR_CPU1(JTextField txtIR_CPU1) {
        this.txtIR_CPU1 = txtIR_CPU1;
    }

    public JTextField getTxtIR_CPU2() {
        return txtIR_CPU2;
    }

    public void setTxtIR_CPU2(JTextField txtIR_CPU2) {
        this.txtIR_CPU2 = txtIR_CPU2;
    }

    public JTextField getTxtPC_CPU1() {
        return txtPC_CPU1;
    }

    public void setTxtPC_CPU1(JTextField txtPC_CPU1) {
        this.txtPC_CPU1 = txtPC_CPU1;
    }

    public JTextField getTxtPC_CPU2() {
        return txtPC_CPU2;
    }

    public void setTxtPC_CPU2(JTextField txtPC_CPU2) {
        this.txtPC_CPU2 = txtPC_CPU2;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClean;
    private javax.swing.JButton btnConfig;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton btnLoadFile;
    private javax.swing.JButton btnNextStep;
    private javax.swing.JButton btnStats;
    private javax.swing.JComboBox<String> cmb_box_MemoryA;
    private javax.swing.JComboBox<String> cmb_box_Planification;
    private javax.swing.JComboBox<String> cmb_box_qbit;
    private javax.swing.JButton cmdButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelQbit;
    private javax.swing.JLabel labelQbit2;
    private javax.swing.JLabel lblInterruptionWarning;
    private javax.swing.JButton start_Btn;
    private javax.swing.JTable tableDisc;
    private javax.swing.JTable tableMemory;
    private javax.swing.JTable tableProcesses;
    private javax.swing.JTextField textInput;
    private javax.swing.JTextField txtAC_CPU1;
    private javax.swing.JTextField txtAC_CPU2;
    private javax.swing.JTextField txtAX_CPU1;
    private javax.swing.JTextField txtAX_CPU2;
    private javax.swing.JTextField txtBX_CPU1;
    private javax.swing.JTextField txtBX_CPU2;
    private javax.swing.JTextField txtCX_CPU1;
    private javax.swing.JTextField txtCX_CPU2;
    private javax.swing.JTextField txtDX_CPU1;
    private javax.swing.JTextField txtDX_CPU2;
    private javax.swing.JTextField txtIR_CPU1;
    private javax.swing.JTextField txtIR_CPU2;
    private javax.swing.JTextField txtPC_CPU1;
    private javax.swing.JTextField txtPC_CPU2;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }
}
